version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
      - redis
    networks:
      - urlshortener-network

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - urlshortener-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"      
    environment:
      - REDIS_PASSWORD=${MEMSTORE_PASSWORD}       
    networks:
      - urlshortener-network

networks:
  urlshortener-network: